# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10.6 on 2018-03-30 09:08
=======
# Generated by Django 1.10.6 on 2019-06-03 05:43
>>>>>>> bfc88405a63c79aa532e43244b9491eecfb0fe4a
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('meet', models.BooleanField()),
=======
                ('meet', models.BooleanField(default=False)),
                ('host_dt', models.DateTimeField(null=True)),
>>>>>>> bfc88405a63c79aa532e43244b9491eecfb0fe4a
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
