# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-08-01 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeet',
            name='zoom_meeting_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
