# Generated by Django 3.0 on 2020-05-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_auto_20191002_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermeet',
            name='zoom_meeting_id',
        ),
        migrations.AddField(
            model_name='usermeet',
            name='meeting_url',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='usermeet',
            name='helper',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='usermeet',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
