# Generated by Django 3.0 on 2020-05-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0004_auto_20200522_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeet',
            name='meeting_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
